#
# Hey, Hey, Hello!
# This is plugin's, of course.. config.
# It's all from me. Have a fun!
# Author: thekuba
#

items: # Support colors by '&' !!! :>
  title: "%vault_prefix%%player_name%"
  profile:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: ""
    commandR: ""
    name: " "
    lore:
      - '&7Balance: &6%vault_eco_balance_commas% $'
      - '&7Kills: &c%statistic_player_kills%'
      - '&7Deaths: &4%statistic_deaths%'
      - ''
  item0:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: "trade {1}"
    commandR: ""
    name: "&7Safe &c&lTrade"
    lore:
      - ''
      - '&7Are you concerned about your interests?'
      - '&7Do you suspect someone is trying to deceive you?'
      - ''
      - '&7Use a secure trade to never fall for any'
      - '&7fat sale or unsecured trade again.'
      - ''
      - '&cClick to offer this person a Trade.'
  item1:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: "is visit {1}"
    commandR: "is warp {1}"
    name: "&7Teleport to &2The Island"
    lore:
      - ''
      - '&cIn order to move to that player''s island,'
      - '&cthat player must have a welcome or warps'
      - '&con his island.'
      - ''
      - '&2LPM, to visit %player_name%''s Island.'
      - '&2PPM, to open that player''s Warp Menu.'
  item2:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: "is coop {1}"
    commandR: "is perms {1}"
    name: "&7Trust player &6%player_name%"
    lore:
      - ''
      - '&7By making a player trusted, you give them'
      - '&7temporary access to your island, which'
      - '&7ends when he, all members of your island'
      - '&7leave, or you kick them with command'
      - '&e/is uncoop %player_name%'
      - ''
      - '&6LPM, to trust this player.'
      - '&6PPM, to change permissions for that player only.'
  gift:
    # In seconds
    cooldown: 10
    name: "&7Gift for &e%player_name%"
    lore:
      - ''
      - '&7Do you want to give this player something?'
      - '&7Just click on the desired item in your'
      - '&7inventory and then confirm the gift by'
      - '&eshift-click &7on it.'
      - ''
      - '&eClick on an item in your inventory.'
    lore-item:
      - ''
      - '&e&m                                                       '
      - '&7To gift this item to this player, click'
      - '&7on it while holding the &eShift &7key.'
  media:
    name: "&3Connected Accounts"
    lore:
      - ''
      - '&7Instagram: &c%ignotus_instagram%'
      - ''
      - '&7YouTube: &f%ignotus_youtube%'
      - ''
      - '&7Twitch: &5%ignotus_twitch%'
      - ''
      - '&7Snapchat: &e%ignotus_snapchat%'
      - ''
      - '&7Discord: &b&l%ignotus_discord%'
      - ''
      - '&7To set your accounts, use the &3/set &7command.'
    # This is the text that displays if someone of media doesn't have a name set.
    if-empty: "&8Unknown"
  blank:
    name: " "
    lore: []
    amount: 1
    material: "GRAY_STAINED_GLASS_PANE"

nametags:
  enable: true

interact:
  enable: true
  antypvptime: 10
  media-long: 25

abyss:
  enable: true
  title: "                &3&lAbyss"
  interval: 300
  lookable: 0
  timer:
    - 120
    - 60
    - 10
  arrow-right:
    name: "&aNext Page"
    lore: []
  arrow-left:
    name: "&cPrevious Page"
    lore: []
  bossbar:
    # set before and after empty for disable bossbar
    time: 30
    before: "§7Items on the ground will be removed in"
    after: "§7Removed §3{1} §7items from the ground! They fell into the §3/abyss§7."

tablist:
  enable: true
  # in ticks, 20 ticks = 1 second
  refreshFrequency: 1
  frequency: 5
  headers:
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&eI &7know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I &eknow&7, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I &eknow&7, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I &eknow&7, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I &eknow&7, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I &eknow&7, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, &eme &7too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me &etoo\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me &etoo\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me &etoo\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
    - "&e&lIgnotus\n\n&7Wow &e%player_name%&7, you look great!\n&7I know, me too\n\n"
  footers:
    - "                                                  \n\n&7Online: &e%server_online% &7Tps: &e%server_tps_1_colored%"