#
# Hey, Hey, Hello!
# This is plugin's, of course.. config.
# It's all from me. Have a fun!
# Author: thekuba
#

messages: # Support colors by '§' only. Sorry :<
  help: "§e§lIgnotus §8- §7very useful minecraft plugin."
  no-permission: "§4» §cYou do not have access to this command."
  error: "§c» §7The operation failed. Contact the administration."
  usage: "§cUse: §7/set {1} <nazwa>"
  usage-admin: "§7Use: §a/set {0} {1} <nazwa>"
  unknown: "§a» §7You can only set names of:\n§a» §aInstagram§7, §aYouTube§7, §aTwitch§7 i §aDiscord"
  player-quit: "§a» §7Sorry, this player has left the server,\n§a» §7please wait until he comes back."
  long: 30
  toolong: "§a» §7That name is too long!\n§a» §7The maximum number of characters is: §a{1}"
  success: "§a» §7Your {0}'s name just set to §a{1}§7."
  success-admin: "§c» §7Value {0} §c{1} §7set to §c{2}§7."
  gift-get: "§a» §7You just got an item from §a{1}§7!"
  gift-get-not-place: "§a» §7You have no space in your inventory, the gift has been dropped."
  gift-give: "§a» §7The item was successfully delivered to §a{1}§7!"
  gift-cooldown: "§a» §7You can give the next gift only in §a{1} §7seconds."

  # Use {1} for amount of cleared items on the ground.
  abyss-open: "§3» §7Removed §3{1} §7items from the ground! They fell into the §3/abyss§7."
  abyss-timer: "§3» §7Items on the ground will be removed in §3{1} §7seconds."
  abyss-last3msg: "§3» §7{1}"
  # You may use {1} for the remaining time.
  abyss-closed: "§3» §7The §3abyss §7is closed for now."
  abyss-isclosing: "§3» §7The §3abyss §7has just been §4closed§7."

items: # Support colors by '&' !!! :>
  title: "%vault_prefix%%player_name%"
  profile:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: ""
    commandR: ""
    name: " "
    lore:
      - '&7Balance: &6%vault_eco_balance_commas% $'
      - '&7Kills: &c%statistic_player_kills%'
      - '&7Deaths: &4%statistic_deaths%'
      - ''
  item0:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: "trade {1}"
    commandR: ""
    name: "&7Safe &c&lTrade"
    lore:
      - ''
      - '&7Are you concerned about your interests?'
      - '&7Do you suspect someone is trying to deceive you?'
      - ''
      - '&7Use a secure trade to never fall for any'
      - '&7fat sale or unsecured trade again.'
      - ''
      - '&cClick to offer this person a Trade.'
  item1:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: "is visit {1}"
    commandR: "is warp {1}"
    name: "&7Teleportacja &2na Wyspę"
    lore:
      - ''
      - '&cAby móc, przenieść się na wyspę tego'
      - '&cgracza, musi on mieć na swojej wyspie'
      - '&ctabliczkę powitalną lub warpy.'
      - ''
      - '&2LPM, aby odwiedzić Wyspę gracza %player_name%.'
      - '&2PPM, aby otworzyć Menu Warpów tej osoby.'
  item2:
    # If command is "", no commands.
    # {1} is nick of receiver.
    commandL: "is coop {1}"
    commandR: "is perms {1}"
    name: "&7Zaufaj graczu &6%player_name%"
    lore:
      - ''
      - '&7Robiąc gracza zaufanym, dajesz mu tymczasowy'
      - '&7dostęp do Twojej wyspy, który kończy się'
      - '&7wraz z wyjściem jego, wszystkich członków'
      - '&7Twojej wyspy lub wyrzuceniu go za pomocą'
      - '&7komendy &e/is uncoop %player_name%'
      - ''
      - '&6LPM, aby zaufać temu graczowi.'
      - '&6PPM, aby zmienić uprawnienia tylko dla tego gracza.'
  gift:
    # In seconds
    cooldown: 10
    name: "&7Gift for &e%player_name%"
    lore:
      - ''
      - '&7Do you want to give this player something?'
      - '&7Just click on the desired item in your'
      - '&7inventory and then confirm the gift'
      - '&7by shift-click on it.'
      - ''
      - '&eClick on an item in your inventory.'
    lore-item:
      - ''
      - '&e&m                                                       '
      - '&7To gift this item to this player, click'
      - '&7on it while holding the &eShift &7key.'
  media:
    name: "&3Connected Accounts"
    lore:
      - ''
      - '&7Instagram: &c%ignotus_instagram%'
      - ''
      - '&7YouTube: &f%ignotus_youtube%'
      - ''
      - '&7Twitch: &5%ignotus_twitch%'
      - ''
      - '&7Snapchat: &e%ignotus_snapchat%'
      - ''
      - '&7Discord: &b&l%ignotus_discord%'
      - ''
      - '&7To set your accounts, use the &3/set &7command.'
    # This is the text that displays if someone of media doesn't have a name set.
    if-empty: ""
  blank:
    name: " "
    lore: []
    amount: 1
    material: "GRAY_STAINED_GLASS_PANE"
nametags:
  enable: true
interact:
  enable: true
  antypvptime: 10
abyss:
  enable: true
  title: "                &3&lAbyss"
  interval: 120
  lookable: 0
  timer:
    - 60
    - 10
  arrow-right:
    name: "&aNastępna Strona"
    lore: []
  arrow-left:
    name: "&cPoprzednia Strona"
    lore: []
  bossbar:
    # set before and after empty for disable bossbar
    time: 10
    before: "§7Itemy z ziemi zostaną usunięte za:"
    after: "§7Usunięto §3{1} §7itemów z ziemi! Trafiły one do §3/otchlan§7i."
tablist:
  enable: true
  # in ticks, 20 ticks = 1 second
  refreshFrequency: 1
  frequency: 5
  headers:
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7--------------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&e-&7-------------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-&e-&7------------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7--&e-&7-----------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7---&e-&7----------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7----&e-&7---------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-----&e-&7--------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7------&e-&7-------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-------&e-&7------------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7--------&e-&7-----------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7---------&e-&7----------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7----------&e-&7---------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-----------&e-&7--------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7------------&e-&7-------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-------------&e-&7------"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7--------------&e-&7-----"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7---------------&e-&7----"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7----------------&e-&7---"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-----------------&e-&7--"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7------------------&e-&7-"
    - "&e&lIgnotus\n\n&7Welcome &e%player_name%&7!\n\n&7-------------------&e-"
  footers:
    - "&7--------------------\n\n&7Online: &e%server_online%"
    - "&e-&7-------------------\n\n&7Online: &e%server_online%"
    - "&7-&e-&7------------------\n\n&7Online: &e%server_online%"
    - "&7--&e-&7-----------------\n\n&7Online: &e%server_online%"
    - "&7---&e-&7----------------\n\n&7Online: &e%server_online%"
    - "&7----&e-&7---------------\n\n&7Online: &e%server_online%"
    - "&7-----&e-&7--------------\n\n&7Online: &e%server_online%"
    - "&7------&e-&7-------------\n\n&7Online: &e%server_online%"
    - "&7-------&e-&7------------\n\n&7Online: &e%server_online%"
    - "&7--------&e-&7-----------\n\n&7Online: &e%server_online%"
    - "&7---------&e-&7----------\n\n&7Online: &e%server_online%"
    - "&7----------&e-&7---------\n\n&7Online: &e%server_online%"
    - "&7-----------&e-&7--------\n\n&7Online: &e%server_online%"
    - "&7------------&e-&7-------\n\n&7Online: &e%server_online%"
    - "&7-------------&e-&7------\n\n&7Online: &e%server_online%"
    - "&7--------------&e-&7-----\n\n&7Online: &e%server_online%"
    - "&7---------------&e-&7----\n\n&7Online: &e%server_online%"
    - "&7----------------&e-&7---\n\n&7Online: &e%server_online%"
    - "&7-----------------&e-&7--\n\n&7Online: &e%server_online%"
    - "&7------------------&e-&7-\n\n&7Online: &e%server_online%"
    - "&7-------------------&e-\n\n&7Online: &e%server_online%"